# Generated by Django 4.0.1 on 2022-01-05 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0002_rename_hero_pk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pk',
            name='alias',
        ),
        migrations.AddField(
            model_name='pk',
            name='description',
            field=models.TextField(default='', max_length=5000, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pk',
            name='haracteristick',
            field=models.TextField(default='', max_length=5000, verbose_name='Характеристики'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pk',
            name='image',
            field=models.TextField(default='', max_length=5000, verbose_name='URL изоображения'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pk',
            name='price',
            field=models.CharField(default=1, max_length=200, verbose_name='Цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pk',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название ноутбука'),
        ),
    ]
