# Generated by Django 4.0.1 on 2022-01-05 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_remove_pk_alias_pk_description_pk_haracteristick_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pk',
            name='image',
        ),
        migrations.AlterField(
            model_name='pk',
            name='name',
            field=models.CharField(max_length=200, verbose_name='название комплектующих'),
        ),
    ]
