# Generated by Django 4.0.1 on 2022-01-05 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0005_remove_pk_haracteristick_pk_displei_pk_nakopiteli_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pk',
            name='image',
            field=models.TextField(default='', max_length=5000, verbose_name='URL изоображения'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pk',
            name='nakopiteli',
            field=models.CharField(max_length=200, verbose_name='Накопитель'),
        ),
        migrations.AlterField(
            model_name='pk',
            name='operativka',
            field=models.CharField(max_length=200, verbose_name='Оперативка'),
        ),
        migrations.AlterField(
            model_name='pk',
            name='processor',
            field=models.CharField(max_length=200, verbose_name='Процессор'),
        ),
        migrations.AlterField(
            model_name='pk',
            name='ves',
            field=models.CharField(max_length=200, verbose_name='Вес'),
        ),
    ]
