# Generated by Django 4.0.1 on 2022-01-11 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0008_sps'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Sps',
        ),
    ]
